application: gaedoodler
version: 1
runtime: python
api_version: 1

handlers:
- url: /match
  script: main.py

- url: /mate
  script: main.py

- url: /stroke
  script: main.py

- url: /update
  script: main.py

- url: .*
  script: main.py
